flaskapp:
  build: ./flask-app/
  command: "python hello.py"
  links:
    - postgres
    - mongo
  volumes:
    - "/vagrant/flask-app:/opt/flask-app"
  env_file: "flask-app/.env"

mongo:
  restart: always
  image: mongo:3.0.2
  volumes_from:
    - data_mongo
  ports:
    - "27017:27017"
  expose:
    - "27017"

postgres:
  restart: always
  image: postgres
  volumes_from:
    - data_pg
  ports:
    - "5432:5432"
  expose:
    - "5432"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - "/www/static"
  links:
    - flaskapp:flaskapp

data_pg:
  image: postgres:latest
  volumes:
    - "/vagrant/data/postgres:/var/lib/postgresql:rw"
  entrypoint: "/bin/true"

data_mongo:
  image: mongo:3.0.2
  volumes:
    - "/vagrant/data/mongo:/var/lib/mongo:rw"
  entrypoint: "/bin/true"